language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

services:
  - elasticsearch

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

install:
  - composer self-update
  - composer install --dev

script:
  - phpunit

notifications:
  email: false
